version: '3.3'
services:
  mysql-database:
    container_name: mysql-spring-name
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'abass'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'abass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'abass'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  my-web-app:
    container_name: amigos-spring-test
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - mysql-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-spring-name:3306/mydatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: abass
      SPRING_DATASOURCE_PASSWORD: abass
# Names our volume
volumes:
  my-db: